name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry: i-07ceb9f6a4187cc41.dkr.ecr.sa-east-1.amazonaws.com/linktree:latest

    - name: Build and push Docker image
      run: |
        docker build -t linktree:latest .
        docker tag linktree i-07ceb9f6a4187cc41.dkr.ecr.sa-east-1.amazonaws.com/linktree:latest
        docker push linktree:latest

    - name: SSH into AWS instance and update container
      uses: appleboy/ssh-action@master
      with:
        host: "ec2-52-67-38-106.sa-east-1.compute.amazonaws.com"
        username: "ec2-user"
        key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        script: |
          docker stop linktree
          docker rm linktree
          docker pull linktree:latest
          docker run -d -p 8501:8501 --name linktree i-07ceb9f6a4187cc41.dkr.ecr.sa-east-1.amazonaws.com/linktree:latest
