name: Deploy anda Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copiar arquivos com SSH
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
        SOURCE: "././"
        REMOTE_HOST: "ec2-18-228-4-121.sa-east-1.compute.amazonaws.com"
        REMOTE_USER: "ec2-user"
        TARGET: "/home/ec2-user"
      
    - name: Build the Docker image
      run: |
        if docker ps | grep -q "linktree"; then
          echo "O contêiner está em execução, parando..."
          docker stop linktree
        else
          echo "O contêiner não está em execução."
          cd linktree
          docker build -t linktree:latest .
          docker run --rm -p 8501:8501 --name linktree linktree:latest
        fi        
