name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copiar arquivos com SSH e atualizar container
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
        SOURCE: "././"
        REMOTE_HOST: "ec2-18-229-118-128.sa-east-1.compute.amazonaws.com"
        REMOTE_USER: "ec2-user"
        TARGET: "/home/ec2-user"
        script: |
          docker stop linktree
          docker build -t linktree:latest .
          docker run --rm -p 8501:8080 --name linktree linketree:latest
